# Commands to start on workspace startup
tasks:
  - name: Local Build Docker
    before: sudo apt-get install -y httpie
    init: |
      sudo docker build -t        local_docker:latest .
      sudo docker run   -d --name local_docker -p 8080:8080  local_docker:latest
    command: |
      sudo docker restart local_docker &> /dev/null
      http  POST  "http://127.0.0.1:8080/post"  browser="webkit" device="random" run="await page.goto('http://whatsmyuseragent.org/',wait_until='commit');result=await page.content()"
      docker logs --since=2m local_docker

  - name: Remote Pull Docker
    init: |
      sudo docker pull          public.ecr.aws/w3s2d0z8/`basename $(pwd)`:master
      docker tag                public.ecr.aws/w3s2d0z8/`basename $(pwd)`:master    remote_docker:latest
      sudo docker run -d --name remote_docker -p 9000:8080 remote_docker:latest
    command: |
      sudo docker restart remote_docker &> /dev/null
      http  POST  "http://127.0.0.1:9000/post"  browser="webkit" device="random" run="await page.goto('http://whatsmyuseragent.org/',wait_until='commit');result=await page.content()"
      docker logs --since=2m remote_docker

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: notify
    name: docker local
  - port: 9000
    onOpen: notify
    name: docker remote
