on:
  push:
    branches:    
      - main
      - master
      - 'releases/**'


name: Deploy to Okteto.

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:

    # Check-out your repository.
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@latest
